Correction Custom Input
AnthoLFB/AnthonyLefebvre_13_26092022 pull request #10
Opened 2023-01-12 17:17 UTC by AnthoLFB

Réduction de la complexité cyclomatique, réécriture des classes CSS.

2023-01-18 12:10 UTC, TBoileau requested changes

2023-01-18 12:10 UTC, TBoileau commented on src/components/CustomInput.jsx
> +                <input className="field-container__input" type={type} id={labelId} required/>
Je pense que tu peux gérer l'attribut "required" avec une petite ternaire non ?

2023-01-18 12:10 UTC, TBoileau commented on src/components/LoginForm.jsx
>                  <div className='warning-content'>
C'est dommage d'avoir un gros 'if' comme ça juste pour une div, un petit shortcut serait apprécié ici

2023-01-23 14:32 UTC, AnthoLFB commented on src/components/LoginForm.jsx
>                  <div className='warning-content'>
Le problème a été corrigé dans la PR concernant la gestion des erreurs sur les form :"https://github.com/AnthoLFB/AnthonyLefebvre_13_26092022/pull/11"

Le code ressemble à ça maintenant : 
`// If there is an error when sending the form, or when logging in, this is displayed to the user.
    const errorToDisplay = (errorStatus ? <Error errorStatus={errorStatus} /> : null);

    return (
        <section className="login">
            <FontAwesomeIcon icon={faCircleUser}/>
            <h1 className="login__title">Sign in</h1>
            <form className="login__form" onSubmit={(e) => getUserToken(e, store)}>
                <CustomInput title={"Username"} type={"email"} labelId={"userEmail"} isRequired={true}/>
                <CustomInput title={"Password"} type={"password"} labelId={"userPassword"} isRequired={true}/>
                <div className="field-container--horizontal">
                    <input className="field-container__input" type="checkbox" id="backUpUserData" />
                    <label className="field-container__label" htmlFor="backUpUserData">Remember Me</label>
                </div>
                <CustomBtn title={"Sign In"} type={"submit"} isActivated={true}/>
            </form>
            {errorToDisplay}
        </section>
    )`

2023-01-23 14:36 UTC, AnthoLFB commented on src/components/LoginForm.jsx
>                  <div className='warning-content'>
Le code a été changé dans la PR concernant la gestion des erreurs sur les form : 

`    return (
        <section className="login">
            <FontAwesomeIcon icon={faCircleUser}/>
            <h1 className="login__title">Sign in</h1>
            <form className="login__form" onSubmit={(e) => getUserToken(e, store)}>
                <CustomInput title={"Username"} type={"email"} labelId={"userEmail"} isRequired={true}/>
                <CustomInput title={"Password"} type={"password"} labelId={"userPassword"} isRequired={true}/>
                <div className="field-container--horizontal">
                    <input className="field-container__input" type="checkbox" id="backUpUserData" />
                    <label className="field-container__label" htmlFor="backUpUserData">Remember Me</label>
                </div>
                <CustomBtn title={"Sign In"} type={"submit"} isActivated={true}/>
            </form>
            {errorToDisplay}
        </section>
    )``

2023-01-23 15:15 UTC, AnthoLFB commented on src/components/CustomInput.jsx
> +                <input className="field-container__input" type={type} id={labelId} required/>
Effectivement, c'est corrigé :)

`let input = isRequired ? <input className="field-container__input" type={type} id={labelId} required/> : <input className="field-container__input" type={type} id={labelId}/>;`

2023-01-23 15:22 UTC, closed without merging